version: "3.8"

services:
  pcoip-client:
    build:
      context: .
      args:
        username: ${username}
        uid: ${uid}
        gid: ${gid}
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - QT_QPA_PLATFORM=wayland
    volumes:
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

